name: 'Generar Diagrama ER y Diccionario'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main



jobs:
  generate-er-diagram:
    name: 'Generar Diagrama ER y Diccionario'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configurar Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Obtener estructura de la base de datos
      run: |
        pip install pymysql
        python scripts/generate_dbml.py

    - name: Instalar dbdiagram-cli
      run: npm install -g dbml-cli

    - name: Generar Diagrama ER
      run: |
        dbml2png database.dbml -o docs/ER_diagram.png

    - name: Generar Diccionario de Datos
      run: python scripts/generate_dictionary.py

    - name: Actualizar BD.md
      run: |
        echo "# Diagrama ER y Diccionario" > docs/BD.md
        echo "![ER Diagram](docs/ER_diagram.png)" >> docs/BD.md
        cat docs/dictionary.md >> docs/BD.md

    - name: Actualizar README.md
      run: |
        sed -i 's|\[BD.md\](docs/BD.md)|[BD.md](docs/BD.md)|g' README.md

    - name: Commit y Push
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "actions@github.com"
        git add docs/ER_diagram.png docs/BD.md README.md
        git commit -m "Actualizar Diagrama ER y Diccionario"
        git push