name: 'Cargar datos CSV a MySQL'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  load-csv:
    name: 'Cargar datos CSV'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install mysql-connector-python pandas

    - name: Cargar datos a MySQL
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
      run: |
        python scripts/load_csv_to_mysql.py